'use client';

import Image from 'next/image';
import { TradingViewWidget } from './TradingViewWidget';

/* ─── HeroMarketPanel ────────────────────────────────────────────────────
   The hero's market panel: a static 4K terminal-chart render (light + dark
   variants, generated by apps/web/scripts/generate-hero-terminal.js) with
   live single-quote widgets floating over it.

   Client feedback round 4: no card chrome — the render has a transparent
   background and fades out subtly on all four sides (CSS mask), so the
   terminal blends straight into the page. The quote cards stay dark in both
   themes. On mobile the cards are scaled down — the TradingView single-quote
   iframe has a fixed internal font size, so a narrower container alone
   renders huge. */

/* Minimal 4-side fade, split over two nested wrappers (horizontal outside,
   vertical inside) so no mask-composite is needed. A 3-stop eased ramp
   (transparent → 55% → opaque over 3.5%) melts the hard edge without any
   visible washed-out band — wider fades read as blur (client feedback). */
const FADE_X =
  '[mask-image:linear-gradient(to_right,transparent,rgba(0,0,0,0.55)_1.5%,black_3.5%,black_96.5%,rgba(0,0,0,0.55)_98.5%,transparent)]';
const FADE_Y =
  '[mask-image:linear-gradient(to_bottom,transparent,rgba(0,0,0,0.55)_1.5%,black_3.5%,black_96.5%,rgba(0,0,0,0.55)_98.5%,transparent)]';

/* Cache-buster for the terminal renders — the file names never change, so
   browsers and the Next image optimizer keep serving stale bytes after a
   regeneration. Bump this whenever generate-hero-terminal.js is re-run. */
const TERMINAL_V = '?v=3';

/* Three quotes on a diagonal: top-start → middle-end → lower-center. */
const QUOTES: Array<{
  symbol: string;
  /** Logical-position classes — start/end so the layout mirrors under RTL. */
  pos: string;
  /** Scale origin (physical, swapped under RTL) so mobile scaling hugs the anchored edge. */
  origin: string;
  /** Hidden on small screens where they would cover the chart. */
  mobileHidden?: boolean;
}> = [
  {
    symbol: 'OANDA:EURUSD',
    pos: 'top-[9%] start-1 md:start-3',
    origin: 'origin-top-left rtl:origin-top-right',
  },
  {
    symbol: 'BITSTAMP:BTCUSD',
    pos: 'top-[36%] end-1 md:end-3',
    origin: 'origin-top-right rtl:origin-top-left',
  },
  {
    symbol: 'OANDA:XAUUSD',
    pos: 'bottom-[17%] start-[35%]',
    origin: 'origin-top-left rtl:origin-top-right',
    mobileHidden: true,
  },
];

export function HeroMarketPanel() {
  return (
    // Slight page-gutter bleed on mobile so the terminal isn't squeezed by
    // the section padding.
    <div className="relative -mx-3 md:mx-0">
      <div className={FADE_X}>
        <div className={`relative h-[340px] md:h-[460px] xl:h-[560px] ${FADE_Y}`}>
          {/* object-right keeps the price scale + rally (the interesting side
            of the render) in frame when the panel is narrower than 16:9 */}
          {/* unoptimized: the PNGs are already rendered at exactly 2x the
              display slot — re-encoding through the image optimizer (WebP +
              a second resample) is what made them look soft. */}
          <Image
            src={`/images/hero-terminal-light.png${TERMINAL_V}`}
            alt=""
            fill
            priority
            unoptimized
            className="object-cover object-right dark:hidden"
          />
          {/* Not priority: display:none in the default (light) theme, so a lazy
              image is never fetched unless dark mode is active — saves ~100 KiB
              on the critical path. Dark-mode visitors get display:block before
              first paint (next-themes applies the class pre-paint), so it still
              loads immediately for them. */}
          <Image
            src={`/images/hero-terminal-dark.png${TERMINAL_V}`}
            alt=""
            fill
            loading="lazy"
            unoptimized
            className="hidden object-cover object-right dark:block"
          />
        </div>
      </div>

      {/* Live quotes layered over the terminal — deliberately no float
          animation (client feedback: it read as glitchy). Pointer events
          never reach TradingView (built-in mask). */}
      {QUOTES.map((q) => (
        <div
          key={q.symbol}
          className={[
            'absolute z-20 w-[172px] md:w-[190px] xl:w-[210px]',
            'scale-[0.72] md:scale-100',
            q.origin,
            'overflow-hidden rounded-[6px] border border-white/10 bg-[#131722]',
            'shadow-[0_6px_20px_-6px_rgba(0,0,0,0.35)]',
            q.pos,
            q.mobileHidden ? 'hidden md:block' : '',
          ]
            .filter(Boolean)
            .join(' ')}
        >
          <TradingViewWidget
            type="single-quote"
            symbol={q.symbol}
            width="100%"
            height={84}
            theme="dark"
            config={{ isTransparent: false }}
          />
        </div>
      ))}
    </div>
  );
}
