/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    'market-analysis': MarketAnalysis;
    news: News;
    'research-reports': ResearchReport;
    'education-content': EducationContent;
    webinars: Webinar;
    'products-instruments': ProductsInstrument;
    'account-types': AccountType;
    faqs: Faq;
    'newsletter-subscribers': NewsletterSubscriber;
    careers: Career;
    'legal-pages': LegalPage;
    awards: Award;
    'company-content': CompanyContent;
    'team-members': TeamMember;
    'webinar-registrations': WebinarRegistration;
    promotions: Promotion;
    'payment-methods': PaymentMethod;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    'site-settings': SiteSetting;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  totpEnabled?: boolean | null;
  totpSecret?: string | null;
  totpTempSecret?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  publishedDate?: string | null;
  category: 'market-news' | 'analysis' | 'tutorials' | 'company-updates';
  author?: string | null;
  excerpt?: string | null;
  featuredImage?: number | Media | null;
  body: {
    [k: string]: unknown;
  }[];
  seoTitle?: string | null;
  seoDescription?: string | null;
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-analysis".
 */
export interface MarketAnalysis {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  publishedDate: string;
  assetCategory: 'forex' | 'commodities' | 'indices' | 'stocks' | 'etfs' | 'crypto';
  analyst?: string | null;
  body: {
    [k: string]: unknown;
  }[];
  chartEmbed?: string | null;
  relatedInstruments?: (number | ProductsInstrument)[] | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-instruments".
 */
export interface ProductsInstrument {
  id: number;
  name: string;
  symbol: string;
  mt5Symbol?: string | null;
  assetClass: 'forex' | 'commodities' | 'indices' | 'stocks' | 'etfs' | 'crypto';
  usesMT5Data?: boolean | null;
  spread?: number | null;
  swapLong?: number | null;
  swapShort?: number | null;
  leverage?: string | null;
  marginRequirement?: number | null;
  contractSize?: number | null;
  tradingHours?: string | null;
  minTradeSize?: number | null;
  pipValue?: number | null;
  tickSize?: number | null;
  sortOrder?: number | null;
  status: 'active' | 'inactive';
  mt5SyncStatus?: ('never' | 'synced' | 'failed') | null;
  mt5LastSyncedAt?: string | null;
  mt5SyncFailureReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  headline: string;
  slug: string;
  source?: string | null;
  sourceUrl?: string | null;
  publishedDate: string;
  category: 'forex' | 'commodities' | 'indices' | 'crypto' | 'company' | 'regulation';
  body?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  status: 'draft' | 'published';
  seoTitle?: string | null;
  seoDescription?: string | null;
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-reports".
 */
export interface ResearchReport {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  publishedDate: string;
  summary?: string | null;
  reportFile: number | Media;
  thumbnail?: number | Media | null;
  isGated?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education-content".
 */
export interface EducationContent {
  id: number;
  title: string;
  slug: string;
  contentType: 'video' | 'audio' | 'ebook' | 'guide' | 'glossary';
  status: 'draft' | 'published';
  isGated?: boolean | null;
  videoEmbed?: string | null;
  audioFile?: number | Media | null;
  pdfFile?: number | Media | null;
  glossaryTerm?: string | null;
  alphabeticalIndex?: string | null;
  body?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  thumbnail?: number | Media | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars".
 */
export interface Webinar {
  id: number;
  title: string;
  slug: string;
  speaker: string;
  speakerBio?: string | null;
  scheduledAt: string;
  timezone?: string | null;
  status: 'upcoming' | 'live' | 'completed' | 'cancelled';
  zoomRegistrationLink?: string | null;
  zoomWebinarId?: string | null;
  replayUrl?: string | null;
  thumbnail?: number | Media | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-types".
 */
export interface AccountType {
  id: number;
  name: string;
  minDeposit: number;
  spreadFrom: string;
  leverage: string;
  platforms: ('mt5' | 'web-trader' | 'mobile')[];
  usesMT5Data?: boolean | null;
  spreadFromNumeric?: number | null;
  commission?: string | null;
  features?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  isPopular?: boolean | null;
  sortOrder?: number | null;
  status: 'active' | 'inactive';
  mt5SyncStatus?: ('never' | 'synced' | 'failed') | null;
  mt5LastSyncedAt?: string | null;
  mt5SyncFailureReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    [k: string]: unknown;
  }[];
  category:
    | 'trading'
    | 'accounts'
    | 'deposits'
    | 'withdrawals'
    | 'platforms'
    | 'regulation'
    | 'general';
  sortOrder?: number | null;
  status: 'active' | 'inactive';
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  locale: 'en' | 'ar';
  status: 'pending' | 'subscribed' | 'unsubscribed';
  source?: string | null;
  consentTimestamp?: string | null;
  consentIpHash?: string | null;
  doubleOptInConfirmed?: boolean | null;
  doubleOptInTimestamp?: string | null;
  externalId?: string | null;
  utmParams?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  confirmToken?: string | null;
  confirmTokenExpiry?: string | null;
  unsubscribeToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  slug: string;
  department:
    | 'engineering'
    | 'design'
    | 'marketing'
    | 'sales'
    | 'operations'
    | 'compliance'
    | 'support'
    | 'finance';
  location: string;
  employmentType: 'full-time' | 'part-time' | 'contract' | 'freelance' | 'internship';
  summary?: string | null;
  body: {
    [k: string]: unknown;
  }[];
  applyUrl?: string | null;
  publishedDate: string;
  sortOrder?: number | null;
  status: 'open' | 'closed';
  seoTitle?: string | null;
  seoDescription?: string | null;
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  slug: string;
  pageType: 'terms' | 'privacy-policy' | 'risk-disclosure' | 'aml-policy' | 'cookie-policy';
  body: {
    [k: string]: unknown;
  }[];
  effectiveDate: string;
  version?: string | null;
  riskWarningBanner?: string | null;
  status: 'draft' | 'published';
  seoTitle?: string | null;
  seoDescription?: string | null;
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  title: string;
  slug: string;
  date: string;
  description?: string | null;
  logo?: number | Media | null;
  externalUrl?: string | null;
  sortOrder?: number | null;
  status: 'published' | 'draft';
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-content".
 */
export interface CompanyContent {
  id: number;
  title: string;
  slug: string;
  section: 'awards' | 'press';
  date: string;
  description?: string | null;
  body?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  externalUrl?: string | null;
  logo?: number | Media | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  slug: string;
  role: string;
  bio?: string | null;
  photo?: number | Media | null;
  sortOrder?: number | null;
  status: 'active' | 'inactive';
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinar-registrations".
 */
export interface WebinarRegistration {
  id: number;
  webinar: number | Webinar;
  name: string;
  email: string;
  locale: 'en' | 'ar';
  registeredAt?: string | null;
  consentIpHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  title: string;
  slug: string;
  tag?: string | null;
  tagColor?: ('accent' | 'amber' | 'blue' | 'purple' | 'red' | 'grey') | null;
  description: string;
  terms?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  isHighlighted?: boolean | null;
  sortOrder?: number | null;
  activeFrom?: string | null;
  activeTo?: string | null;
  status: 'active' | 'inactive';
  seoTitle?: string | null;
  seoDescription?: string | null;
  translationKey?: string | null;
  locale: 'en' | 'ar';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-methods".
 */
export interface PaymentMethod {
  id: number;
  name: string;
  methodType: 'card' | 'bank' | 'ewallet' | 'crypto' | 'local';
  logo?: number | Media | null;
  depositTime?: string | null;
  withdrawalTime?: string | null;
  minDeposit?: string | null;
  fee?: string | null;
  notes?: string | null;
  sortOrder?: number | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  mt5SyncEnabled?: boolean | null;
  mt5ApiEndpoint?: string | null;
  mt5ApiKey?: string | null;
  mt5RefreshIntervalSecs?: number | null;
  kpiStats?:
    | {
        valueEn: string;
        valueAr: string;
        labelEn: string;
        labelAr: string;
        id?: string | null;
      }[]
    | null;
  socialProofLogos?:
    | {
        logo: number | Media;
        altEn?: string | null;
        altAr?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  downloadMt5Windows?: string | null;
  downloadMt5Mac?: string | null;
  downloadMt5Ios?: string | null;
  downloadMt5Android?: string | null;
  downloadWebTrader?: string | null;
  contactEmail?: string | null;
  contactEmailCompliance?: string | null;
  contactPhone?: string | null;
  contactAddressEn?: string | null;
  contactAddressAr?: string | null;
  supportHoursEn?: string | null;
  supportHoursAr?: string | null;
  socialFacebook?: string | null;
  socialX?: string | null;
  socialLinkedIn?: string | null;
  socialInstagram?: string | null;
  socialYoutube?: string | null;
  socialTelegram?: string | null;
  socialTiktok?: string | null;
  riskBannerEnabled?: boolean | null;
  riskBannerEn?: string | null;
  riskBannerAr?: string | null;
  navEn?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  navAr?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerEn?:
    | {
        heading?: string | null;
        links?:
          | {
              label?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerAr?:
    | {
        heading?: string | null;
        links?:
          | {
              label?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  riskDisclaimerEn?: string | null;
  riskDisclaimerAr?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}

declare module 'payload' {
  // @ts-ignore TS2300 — payload 2.x declares GeneratedTypes as a type alias; augmentation conflicts on this TS version
  export interface GeneratedTypes extends Config {}
}
