export interface CountryInfo {
  name: string;
  iso2: string;
  code: string;
  flag: string;
  minDigits: number;
  maxDigits: number;
  placeholder?: string;
}

export const ALL_COUNTRIES: CountryInfo[] = [
  {
    name: 'India',
    iso2: 'IN',
    code: '+91',
    flag: '🇮🇳',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits (e.g. 9876543210)',
  },
  {
    name: 'United Arab Emirates',
    iso2: 'AE',
    code: '+971',
    flag: '🇦🇪',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits (e.g. 501234567)',
  },
  {
    name: 'Saudi Arabia',
    iso2: 'SA',
    code: '+966',
    flag: '🇸🇦',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits (e.g. 501234567)',
  },
  {
    name: 'United Kingdom',
    iso2: 'GB',
    code: '+44',
    flag: '🇬🇧',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits (e.g. 7911123456)',
  },
  {
    name: 'United States',
    iso2: 'US',
    code: '+1',
    flag: '🇺🇸',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits (e.g. 2025550123)',
  },
  {
    name: 'Kuwait',
    iso2: 'KW',
    code: '+965',
    flag: '🇰🇼',
    minDigits: 8,
    maxDigits: 8,
    placeholder: '8 digits (e.g. 91234567)',
  },
  {
    name: 'Qatar',
    iso2: 'QA',
    code: '+974',
    flag: '🇶🇦',
    minDigits: 8,
    maxDigits: 8,
    placeholder: '8 digits (e.g. 33123456)',
  },
  {
    name: 'Bahrain',
    iso2: 'BH',
    code: '+973',
    flag: '🇧🇭',
    minDigits: 8,
    maxDigits: 8,
    placeholder: '8 digits (e.g. 39123456)',
  },
  {
    name: 'Oman',
    iso2: 'OM',
    code: '+968',
    flag: '🇴🇲',
    minDigits: 8,
    maxDigits: 8,
    placeholder: '8 digits (e.g. 91234567)',
  },
  {
    name: 'Egypt',
    iso2: 'EG',
    code: '+20',
    flag: '🇪🇬',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits (e.g. 1012345678)',
  },
  {
    name: 'Jordan',
    iso2: 'JO',
    code: '+962',
    flag: '🇯🇴',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits (e.g. 791234567)',
  },
  {
    name: 'Lebanon',
    iso2: 'LB',
    code: '+961',
    flag: '🇱🇧',
    minDigits: 8,
    maxDigits: 8,
    placeholder: '8 digits (e.g. 70123456)',
  },
  {
    name: 'Iraq',
    iso2: 'IQ',
    code: '+964',
    flag: '🇮🇶',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'Morocco',
    iso2: 'MA',
    code: '+212',
    flag: '🇲🇦',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Algeria',
    iso2: 'DZ',
    code: '+213',
    flag: '🇩🇿',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Tunisia',
    iso2: 'TN',
    code: '+216',
    flag: '🇹🇳',
    minDigits: 8,
    maxDigits: 8,
    placeholder: '8 digits',
  },
  {
    name: 'Malaysia',
    iso2: 'MY',
    code: '+60',
    flag: '🇲🇾',
    minDigits: 9,
    maxDigits: 10,
    placeholder: '9-10 digits',
  },
  {
    name: 'Singapore',
    iso2: 'SG',
    code: '+65',
    flag: '🇸🇬',
    minDigits: 8,
    maxDigits: 8,
    placeholder: '8 digits',
  },
  {
    name: 'Indonesia',
    iso2: 'ID',
    code: '+62',
    flag: '🇮🇩',
    minDigits: 10,
    maxDigits: 12,
    placeholder: '10-12 digits',
  },
  {
    name: 'Thailand',
    iso2: 'TH',
    code: '+66',
    flag: '🇹🇭',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Vietnam',
    iso2: 'VN',
    code: '+84',
    flag: '🇻🇳',
    minDigits: 9,
    maxDigits: 10,
    placeholder: '9-10 digits',
  },
  {
    name: 'Philippines',
    iso2: 'PH',
    code: '+63',
    flag: '🇵🇭',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'Germany',
    iso2: 'DE',
    code: '+49',
    flag: '🇩🇪',
    minDigits: 10,
    maxDigits: 11,
    placeholder: '10-11 digits',
  },
  {
    name: 'France',
    iso2: 'FR',
    code: '+33',
    flag: '🇫🇷',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Italy',
    iso2: 'IT',
    code: '+39',
    flag: '🇮🇹',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'Spain',
    iso2: 'ES',
    code: '+34',
    flag: '🇪🇸',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Netherlands',
    iso2: 'NL',
    code: '+31',
    flag: '🇳🇱',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Switzerland',
    iso2: 'CH',
    code: '+41',
    flag: '🇨🇭',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Sweden',
    iso2: 'SE',
    code: '+46',
    flag: '🇸🇪',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Norway',
    iso2: 'NO',
    code: '+47',
    flag: '🇳🇴',
    minDigits: 8,
    maxDigits: 8,
    placeholder: '8 digits',
  },
  {
    name: 'Denmark',
    iso2: 'DK',
    code: '+45',
    flag: '🇩🇰',
    minDigits: 8,
    maxDigits: 8,
    placeholder: '8 digits',
  },
  {
    name: 'Finland',
    iso2: 'FI',
    code: '+358',
    flag: '🇫🇮',
    minDigits: 9,
    maxDigits: 10,
    placeholder: '9-10 digits',
  },
  {
    name: 'Poland',
    iso2: 'PL',
    code: '+48',
    flag: '🇵🇱',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Austria',
    iso2: 'AT',
    code: '+43',
    flag: '🇦🇹',
    minDigits: 10,
    maxDigits: 11,
    placeholder: '10-11 digits',
  },
  {
    name: 'Belgium',
    iso2: 'BE',
    code: '+32',
    flag: '🇧🇪',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Portugal',
    iso2: 'PT',
    code: '+351',
    flag: '🇵🇹',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Greece',
    iso2: 'GR',
    code: '+30',
    flag: '🇬🇷',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'Ireland',
    iso2: 'IE',
    code: '+353',
    flag: '🇮🇪',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Turkey',
    iso2: 'TR',
    code: '+90',
    flag: '🇹🇷',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'Australia',
    iso2: 'AU',
    code: '+61',
    flag: '🇦🇺',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'New Zealand',
    iso2: 'NZ',
    code: '+64',
    flag: '🇳🇿',
    minDigits: 8,
    maxDigits: 10,
    placeholder: '8-10 digits',
  },
  {
    name: 'Canada',
    iso2: 'CA',
    code: '+1',
    flag: '🇨🇦',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'Brazil',
    iso2: 'BR',
    code: '+55',
    flag: '🇧🇷',
    minDigits: 10,
    maxDigits: 11,
    placeholder: '10-11 digits',
  },
  {
    name: 'Mexico',
    iso2: 'MX',
    code: '+52',
    flag: '🇲🇽',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'Argentina',
    iso2: 'AR',
    code: '+54',
    flag: '🇦🇷',
    minDigits: 10,
    maxDigits: 11,
    placeholder: '10-11 digits',
  },
  {
    name: 'Chile',
    iso2: 'CL',
    code: '+56',
    flag: '🇨🇱',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Colombia',
    iso2: 'CO',
    code: '+57',
    flag: '🇨🇴',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'South Africa',
    iso2: 'ZA',
    code: '+27',
    flag: '🇿🇦',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Nigeria',
    iso2: 'NG',
    code: '+234',
    flag: '🇳🇬',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'Kenya',
    iso2: 'KE',
    code: '+254',
    flag: '🇰🇪',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Ghana',
    iso2: 'GH',
    code: '+233',
    flag: '🇬🇭',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'China',
    iso2: 'CN',
    code: '+86',
    flag: '🇨🇳',
    minDigits: 11,
    maxDigits: 11,
    placeholder: '11 digits',
  },
  {
    name: 'Japan',
    iso2: 'JP',
    code: '+81',
    flag: '🇯🇵',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'South Korea',
    iso2: 'KR',
    code: '+82',
    flag: '🇰🇷',
    minDigits: 9,
    maxDigits: 10,
    placeholder: '9-10 digits',
  },
  {
    name: 'Hong Kong',
    iso2: 'HK',
    code: '+852',
    flag: '🇭🇰',
    minDigits: 8,
    maxDigits: 8,
    placeholder: '8 digits',
  },
  {
    name: 'Taiwan',
    iso2: 'TW',
    code: '+886',
    flag: '🇹🇼',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Pakistan',
    iso2: 'PK',
    code: '+92',
    flag: '🇵🇰',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'Bangladesh',
    iso2: 'BD',
    code: '+880',
    flag: '🇧🇩',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
  {
    name: 'Sri Lanka',
    iso2: 'LK',
    code: '+94',
    flag: '🇱🇰',
    minDigits: 9,
    maxDigits: 9,
    placeholder: '9 digits',
  },
  {
    name: 'Nepal',
    iso2: 'NP',
    code: '+977',
    flag: '🇳🇵',
    minDigits: 10,
    maxDigits: 10,
    placeholder: '10 digits',
  },
];
